# Generated by Django 5.0.1 on 2024-01-10 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('description', models.CharField(default='', max_length=500)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('tickets_available', models.PositiveIntegerField(default=0)),
                ('image_url', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Payment_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=10)),
                ('uid', models.CharField(max_length=50)),
                ('is_seller', models.BooleanField(default=False)),
                ('bio', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('billing_address', models.CharField(default='', max_length=250)),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eventageousapi.payment_type')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eventageousapi.user')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eventageousapi.event')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventageousapi.order')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventageousapi.ticket')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventageousapi.user'),
        ),
    ]
