# Generated by Django 5.0.1 on 2024-01-17 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventageousapi', '0003_alter_ticket_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_ticket',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_tickets', to='eventageousapi.order'),
        ),
        migrations.AlterField(
            model_name='order_ticket',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_orders', to='eventageousapi.ticket'),
        ),
    ]
