# Generated by Django 5.0.1 on 2024-01-20 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventageousapi', '0004_alter_order_ticket_order_alter_order_ticket_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.CharField(blank=True, max_length=26, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_ticket', to='eventageousapi.event'),
        ),
    ]
